name: dask-odsc
channels:
 - defaults
 - conda-forge
dependencies:
 - dask=0.19.4
 - dask-ml=0.11.0
 - distributed=1.23.3
 - graphviz
 - h5py=2.8.0
 - ipywidgets=7.4.2
 - jupyter=1.0.0
 - jupyterlab=0.35.2
 - matplotlib=3.0.0
 - memory_profiler=0.54.0
 - numba=0.40.0
 - numpy=1.15.3
 - pandas=0.23.4
 - pillow=5.3.0
 - pytables=3.4.4
 - python=3.7
 - s3fs=0.1.6
 - scikit-image=0.14.0
 - scikit-learn=0.20.0
 - scipy=1.1.0
 - snakeviz=1.0.0
 - gcsfs=0.1.2
 - python-graphviz=0.8.4
 - nodejs=10.8.0
 - zarr=2.2.0
 - pip:
   - kubernetes
   - git+https://github.com/dask/dask-kubernetes.git
